sudo: required
services:
 - docker
language: python
python:
 - 2.7
 - pypy
 - 3.5

matrix:
  exclude:
    - python: 3.5
    - python: pypy
  include:
    - python: 3.5
      env: RUN_LINTS=true
    - python: 2.7
      env: RUN_LINTS=true
    - python: 2.7
      env: RUN_TESTS=true
    - python: pypy
      env: RUN_TESTS=true
cache: pip

before_install: bash -xe travis/before-install.sh
script: bash -xe travis/test-script.sh
