services:
 - postgresql
 - elasticsearch
addons:
  apt:
    sources:
      - elasticsearch-5.x
    packages:
      - elasticsearch
      - oracle-java8-set-default
language: python
python:
 - 2.7
 - 3.6

matrix:
  include:
    - python: 3.6
      env: RUN_LINTS=true
    - python: 2.7
      env: RUN_LINTS=true
cache: pip

before_install: bash -xe travis/before-install.sh
install: pip install -r requirements-dev.txt
script: bash -xe travis/test-script.sh
