version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true

environment:
  PGUSER: postgres
  PGPASSWORD: Password12!
  PGSQL_PATH: C:\Program Files\PostgreSQL\9.6
  POSTGRES_ENV_POSTGRES_USER: postgres
  POSTGRES_ENV_POSTGRES_PASSWORD: Password12!

  matrix:
    - PYTHON: C:\Python27-x64

services:
  - postgresql

before_test:
  - SET PATH=%PGSQL_PATH%\bin;%PATH%
  - createdb pacifica_metadata
  - ps: >
      Start-Process $env:PYTHON\python.exe -ArgumentList "$env:PYTHON\scripts\MetadataServer.py" -WorkingDirectory "travis";
      Invoke-WebRequest https://github.com/pacifica/pacifica-metadata/archive/master.zip -OutFile pacifica-metadata.zip;
      Expand-Archive pacifica-metadata.zip -DestinationPath C:\pacifica-metadata;
      sleep 10;
      Invoke-WebRequest http://localhost:8121/users;
      cd C:\pacifica-metadata\pacifica-metadata-master;
      echo '======';
      cat test_files/proposals.json;
      echo '======';
      & "$env:PYTHON\python.exe" -m test_files.loadit;
      cd C:\projects\pacifica-policy;
      cat test_files/proposals.json;
      echo '======';
      & "$env:PYTHON\python.exe" test_files/loadit.py;

install:
  - ps: 'Invoke-WebRequest -Uri "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.5.zip" -OutFile "elasticsearch.zip"'
  - ps: 'Expand-Archive "elasticsearch.zip" -DestinationPath "C:\elasticsearch"'
  - ps: 'Start-Process C:\elasticsearch\elasticsearch-5.6.5\bin\elasticsearch'
  - '%PYTHON%\python.exe -m pip install -r requirements-dev.txt'

build: off

test_script:
  - ps: >
      & "$env:PYTHON\python.exe" -m coverage run --include='policy/*' -m pytest -v policy;
      & "$env:PYTHON\python.exe" -m coverage run --include='policy/*' -a PolicyServer.py --stop-after-a-moment;
      & "$env:PYTHON\python.exe" -m coverage report -m --fail-under=100;
